### PR TITLE
Improve drawTracer

### PR DESCRIPTION
**Pull request by Vertex-Client**
Compatibility with flame, redstone and critical particle type

### CODE REVIEW

**Comment by ArceusMatt** [comment]
I think it's fine with flame because flame can be seen either at night or day.

**Comment by Vertex-Client** [comment]
Well, I also fixed the code since you changed the function content (you removed the whole particle functionality by changing it).

**Comment by Vertex-Client** [comment]
It's just extra, default is still flame. ;)

**Comment by ArceusMatt** [comment]
What's the differance between using your functionality or my button changing one variable where the particleType is? Won't it have the same output either way?

**Comment by ArceusMatt** [comment]
I believe that instead of getTile, this should be a Player ESP:
var mobs = Entity.getall();
var newX= Entity.getX(mobs[e]) - getPlayerX();
var newY = Entity.getY(mobs[e]) - getPlayerY();
var newZ = Entity.getZ(mobs[e]) - getPlayerZ();
for (var e = 0; e < mobs.length; e++) {
//65 ID of player
if(Entity.getEntityTypeId(mobs[e]) == 65){
//drawTracer here
}
}
What do you think?

**Comment by Vertex-Client** [comment]
Almost correct, but the newX/Y/Z should be defined within the for loop itself. :)
The rest of your function should work, but you should change var mobs to Entity.get**A**ll.

**Comment by ArceusMatt** [comment]
I see, well i'll add this after the commit i'm currently coding right now. Thanks!

**Pull request closed without merging**
